name: flutter_recipe_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.3.2
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^1.2.4
  get_it: ^4.0.4
  logger: ^0.9.2
  responsive_builder: ^0.2.0+2
  stacked: ^1.7.6
  stacked_services: ^0.5.4+2
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/calamares.jpg
    - assets/images/crispy_pata.jpg
    - assets/images/pochero.jpg
    - assets/images/banana.png
    - assets/images/beef_caldereta.jpg
    - assets/images/beef.png
    - assets/images/black_pepper.png
    - assets/images/bokchoy.png
    - assets/images/butter.png
    - assets/images/cabbage.png
    - assets/images/carrot.png
    - assets/images/cheese.png
    - assets/images/chicken_adobo.jpg
    - assets/images/chili.png
    - assets/images/egg.png
    - assets/images/embutido.jpg
    - assets/images/flour.png
    - assets/images/garlic.png
    - assets/images/green_beans.png
    - assets/images/green_bell.png
    - assets/images/grilled_pork_ribs.jpg
    - assets/images/grilled_seafood.jpg
    - assets/images/ground_pork.png
    - assets/images/lemon.png
    - assets/images/oil.png
    - assets/images/onion.png
    - assets/images/pancit_canton.jpg
    - assets/images/pork_sisig.jpg
    - assets/images/pork.png
    - assets/images/potato.png
    - assets/images/raisins.png
    - assets/images/red_bell.png
    - assets/images/red_pepper.png
    - assets/images/salt.png
    - assets/images/sausage.png
    - assets/images/smoked_salmon.jpg
    - assets/images/squid.png
    - assets/images/sweet_and_sour_chicken_poultry.jpg
    - assets/images/tomato.png
    - assets/images/yellow_onion.png
    - assets/response.json

#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
